#!/bin/bash

set -Eeuo pipefail

export GOPATH=$HOME

pushd "$(dirname "$0")" > /dev/null 2>&1

cd ../..
CERTIFIER_PROTOTYPE="$(pwd)"; export CERTIFIER_PROTOTYPE

popd

export KEYSTONE_EXAMPLE_DIR=$CERTIFIER_PROTOTYPE/sample_apps/simple_app_under_keystone
export KEYSTONE_SRC=$CERTIFIER_PROTOTYPE/src/keystone

env | grep -E 'CERTIFIER_PROTOTYPE|KEYSTONE_EXAMPLE_DIR|KEYSTONE_SRC'

# Make directories
set -x
rm -rf $KEYSTONE_EXAMPLE_DIR/{provisioning,service,app1_data,app2_data}

mkdir -p $KEYSTONE_EXAMPLE_DIR/provisioning
mkdir -p $KEYSTONE_EXAMPLE_DIR/service
mkdir -p $KEYSTONE_EXAMPLE_DIR/app1_data
mkdir -p $KEYSTONE_EXAMPLE_DIR/app2_data

cd $KEYSTONE_SRC

# You should see two binary files for the private signing key for the keystone shim and its self-signed cert
# named emulated_keystone_key.bin and emulated_keystone_key_cert.bin.  If not, build the shim test and run it.

make -f shim_test.mak
./keystone_test.exe
cp -p $KEYSTONE_SRC/emulated_keystone_key.bin $KEYSTONE_SRC/emulated_keystone_key_cert.bin $KEYSTONE_EXAMPLE_DIR/provisioning


#build the utilities
cd $CERTIFIER_PROTOTYPE
cd utilities
make -f cert_utility.mak
make -f policy_utilities.mak


#generate the keys
cd $KEYSTONE_EXAMPLE_DIR/provisioning

$CERTIFIER_PROTOTYPE/utilities/cert_utility.exe --operation=generate-policy-key-and-test-keys \
    --policy_key_output_file=policy_key_file.bin --policy_cert_output_file=policy_cert_file.bin \
    --platform_key_output_file=platform_key_file.bin --attest_key_output_file=attest_key_file.bin


# embed policy key and compile app
cd $KEYSTONE_EXAMPLE_DIR/provisioning

$CERTIFIER_PROTOTYPE/utilities/embed_policy_key.exe --input=policy_cert_file.bin --output=../policy_key.cc

# make app and compute app measurement
cd $KEYSTONE_EXAMPLE_DIR
make -f keystone_example_app.mak


# write the policy
cd $KEYSTONE_EXAMPLE_DIR/provisioning

# policyKey says the attestationKey is-trusted-for-attestation
$CERTIFIER_PROTOTYPE/utilities/make_unary_vse_clause.exe --cert_subject=emulated_keystone_key_cert.bin \
  --verb="is-trusted-for-attestation" --output=ts1.bin

$CERTIFIER_PROTOTYPE/utilities/make_indirect_vse_clause.exe --key_subject=policy_key_file.bin \
  --verb="says" --clause=ts1.bin --output=vse_policy1.bin

# Get Measurement: policy key says measurement is-trusted
$CERTIFIER_PROTOTYPE/utilities/measurement_utility.exe --type=hash --input=../keystone_example_app.exe \
      --output=example_app.measurement

$CERTIFIER_PROTOTYPE/utilities/make_unary_vse_clause.exe --key_subject="" \
  --measurement_subject=example_app.measurement --verb="is-trusted" \
  --output=ts2.bin

$CERTIFIER_PROTOTYPE/utilities/make_indirect_vse_clause.exe --key_subject=policy_key_file.bin \
  --verb="says" --clause=ts2.bin --output=vse_policy2.bin

$CERTIFIER_PROTOTYPE/utilities/make_signed_claim_from_vse_clause.exe --vse_file=vse_policy1.bin \
  --duration=9000 --private_key_file=policy_key_file.bin --output=signed_claim_1.bin

$CERTIFIER_PROTOTYPE/utilities/make_signed_claim_from_vse_clause.exe \
  --vse_file=vse_policy2.bin --duration=9000 \
  --private_key_file=policy_key_file.bin --output=signed_claim_2.bin

$CERTIFIER_PROTOTYPE/utilities/package_claims.exe --input=signed_claim_1.bin,signed_claim_2.bin\
  --output=policy.bin

$CERTIFIER_PROTOTYPE/utilities/print_packaged_claims.exe --input=policy.bin

# -----------------------------------------------------------------------------
# NOTE: This arrangement is critical for this app to run cleanly.
#       As we are working with a shim, simpleserver needs to be built with
#       emulated key/cert bin files. So, provision them first.
# provision service and apps
# -----------------------------------------------------------------------------
cd $KEYSTONE_EXAMPLE_DIR/provisioning
cp  -p ./* $KEYSTONE_EXAMPLE_DIR/service
cp  -p ./* $KEYSTONE_EXAMPLE_DIR/app1_data
cp  -p ./* $KEYSTONE_EXAMPLE_DIR/app2_data

#compile the server
cd $CERTIFIER_PROTOTYPE/certifier_service/certprotos

protoc --go_opt=paths=source_relative --go_out=. --go_opt=M=certifier.proto ./certifier.proto

cd $CERTIFIER_PROTOTYPE/certifier_service/oelib
make dummy

cd $CERTIFIER_PROTOTYPE/certifier_service/graminelib
make dummy

cd $CERTIFIER_PROTOTYPE/certifier_service/isletlib
make dummy

cd $CERTIFIER_PROTOTYPE/certifier_service/teelib
make

cd $CERTIFIER_PROTOTYPE/certifier_service

go build simpleserver.go

#run server
cd $KEYSTONE_EXAMPLE_DIR/service

$CERTIFIER_PROTOTYPE/certifier_service/simpleserver --policyFile=policy.bin --readPolicy=true &

sleep 5

# initialize client app
cd $KEYSTONE_EXAMPLE_DIR

$KEYSTONE_EXAMPLE_DIR/keystone_example_app.exe --print_all=true \
      --operation=cold-init --data_dir=./app1_data/ --measurement_file="example_app.measurement" \
      --policy_store_file=policy_store

sleep 5

# get client app certified
$KEYSTONE_EXAMPLE_DIR/keystone_example_app.exe --print_all=true \
      --operation=get-certified --data_dir=./app1_data/ --measurement_file="example_app.measurement" \
      --policy_store_file=policy_store

sleep 5

# initialize server app
$KEYSTONE_EXAMPLE_DIR/keystone_example_app.exe --print_all=true \
      --operation=cold-init --data_dir=./app2_data/ --measurement_file="example_app.measurement" \
      --policy_store_file=policy_store

sleep 5

# get server app certified
$KEYSTONE_EXAMPLE_DIR/keystone_example_app.exe --print_all=true \
      --operation=get-certified --data_dir=./app2_data/ --measurement_file="example_app.measurement" \
       --policy_store_file=policy_store

sleep 5

#run the app
cd $KEYSTONE_EXAMPLE_DIR

$KEYSTONE_EXAMPLE_DIR/keystone_example_app.exe --print_all=true --operation=run-app-as-server --data_dir=./app2_data/ \
      --policy_store_file=policy_store --measurement_file="example_app.measurement" &

sleep 5

cd $KEYSTONE_EXAMPLE_DIR

$KEYSTONE_EXAMPLE_DIR/keystone_example_app.exe --print_all=true --operation=run-app-as-client --data_dir=./app1_data/ \
      --policy_store_file=policy_store --measurement_file="example_app.measurement"

